### ISSUE TITLE
Warning: spawn unknown

### ISSUE THREAD

**Issue by MarkusPint** [tdeekens/grunt-browsersnapsy#1]
Running "browsersnapsy:task" (browsersnapsy) task
Warning: spawn UNKNOWN Use --force to continue.

I am using Win 7.

**Comment by tdeekens** [comment]
I'll look into it. Cheers for reporting!

**Comment by MarkusPint** [comment]
Heh last one was not related to browsersnapsy, but browserstacktunnel-wrapper.

But now there is a new issue:
Requesting screenshots finished.
Fatal error: Unexpected token <

Occurs on line 127. "data" variable equals:

`<html><body>You are being <a href="https://www.browserstack.com/screenshots/1234">redirected</a>.</body></html>
`

I replaced job ID with 1234.

Is it a configuration error by me or you haven't had time to update the repo? :)

**Comment by MarkusPint** [comment]
Making PR

**Comment by tdeekens** [comment]
Thanks a lot. Just leaving work and will merge as soon as possible.

**Comment by tdeekens** [comment]
Closed with #3.
